services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: crowd_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sithum123
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: