// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzavadcpqjhpcyjuvebo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YXZhZGNwcWpocGN5anV2ZWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MTY0MDIsImV4cCI6MjA3MzE5MjQwMn0.NjXFdFoKByQIkoNAEvRR6jlW3YDVxBHeQKktLz5SO5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});